# Generated by Django 2.1.2 on 2018-11-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
        ('chat', '0003_auto_20181104_1215'),
    ]

    operations = [
    ]
