# Generated by Django 2.1.2 on 2018-12-12 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20181212_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_hash',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
